CREATE TABLE KHACHHANG
(
 MAKH  char(4) PRIMARY KEY,
 HOTEN varchar(40),
 DCHI  varchar(50),
 SODT  varchar(20),
 NGSINH datetime,
 NGDK  datetime,
 DOANHSO int
);
CREATE TABLE NHANVIEN
(
 MANV  char(4)PRIMARY KEY,
 HOTEN varchar(40),
 SODT  varchar(20),
 NGVL  datetime
);
CREATE TABLE SANPHAM
(
 MASP  char(4)PRIMARY KEY,
 TENSP varchar(40),
 DVT  varchar(20),
 NUOCSX varchar(40),
 GIA  int
);
CREATE TABLE HOADON
(
 SOHD  int PRIMARY KEY,
 NGHD  datetime,
 MAKH  char(4),
 FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
 MANV  char(4),
 FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
 TRIGIA int
);
CREATE TABLE CTHD
(
 SOHD  int,
 FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
 MASP  char(4),
 FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
 SL  int,
 CONSTRAINT PK_CTHD PRIMARY KEY (SOHD,MASP)
);

ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20);
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT ;
ALTER TABLE SANPHAM Change COLUMN GHICHU type VARCHAR(100);
ALTER TABLE SANPHAM DROP COLUMN GHICHU;
ALTER TABLE KHACHHANG change COLUMN LOAIKH type VARCHAR(50);
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_DVT CHECK(DVT='CAY'OR DVT='CAI'OR DVT='HOP'OR DVT='QUYEN'OR DVT='CHUC');
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_GIA CHECK(GIA>=500);
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGDK CHECK (NGDK>NGSINH);
